# Generated by Django 6.0.3 on 2026-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Desciption', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Category', models.CharField(default='General', max_length=50)),
                ('Stock', models.IntegerField(default=0)),
                ('Created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
